feat: add Pinecone serverless index templates
pulumi/templates pull request #727
Opened 2024-01-13 11:26 UTC by dirien

Hi,

This PR adds starter templates for the Pinecone provider only for serverless indexes

2024-01-13 21:58 UTC, scottslowe requested changes
This looks good (only one minor change needed on the Python program), but we'll need to include a C# template here as well (or follow up very quickly with a C# template).

2024-01-13 21:58 UTC, scottslowe commented on pinecone-serverless-python/__main__.py
> +"""An OpenStack Python Pulumi program"""
```suggestion
"""A minimal Pinecone Serverless Python Pulumi program"""
```

2024-01-14 19:18 UTC, dirien commented
Hi @scottslowe,

thanks for the feedback and review! I must forgot the C# example, but now it is added! 

Looking forward for you review.

2024-01-14 23:24 UTC, scottslowe approved these changes

2024-01-15 05:55 UTC, merged

2024-01-15 17:34 UTC, cnunciato commented
@dirien Can we build a Java template also?

2024-01-15 17:35 UTC, dirien commented
> @dirien Can we build a Java template also?

@cnunciato we did not generated a Java SDK for the moment!

2024-01-15 17:58 UTC, cnunciato commented
How does one use these templates? When I run the TypeScript template with an API key for example, I get this:

```
Diagnostics:
  pulumi:pulumi:Stack (pinecone-serverless-typescript-03f0d18-dev):
    error: update failed

  pinecone:index:PineconeIndex (my-example-index):
    error: Failed to get Pinecone index: example-index-ts with http error code: 404
    error: failed to get Pinecone index: example-index-ts
```

Should we prompt for some of these values? Should we revisit the naming across these to be more consistent?

2024-01-15 18:57 UTC, cnunciato commented
Chatted with @dirien and the error may be because my account doesn't have early-access perms for this feature. #729 renames the templates `pinecone-$language`.